"use client"

import type { Metadata } from "next"
import { usePathname } from "next/navigation"
import "./globals.css"
import TopNav from "@/components/navigation/TopNav"
import HomeHeading from "@/components/pageHeadings/HomeHeading"
import OtherHeading from "@/components/pageHeadings/OtherHeading"

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  //Gets router to check if home page or not
  const pathname = usePathname()
  const isHomePage = pathname === "/"

  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <TopNav />
        <main className="relative flex-grow">
          {isHomePage ? <HomeHeading /> : <OtherHeading />}
          <div className="flex">

            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
