import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/components/navigation/TopNav";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <TopNav />
        <main className="relative flex-grow">
          <div className="flex">

            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
